#!/bin/bash

server=
emailAddress=

mv /tmp/emailAlias /tmp/emailAlias_previous

/usr/bin/curl -s http://$server/emailAddress.txt > /tmp/emailAlias

emailAlias=`cat /tmp/emailAlias`
emailAlias_previous=`cat /tmp/emailAlias_previous`

/opt/zimbra/bin/zmprov addAccountAlias $emailAddress $emailAlias
/opt/zimbra/bin/zmprov removeAccountAlias $emailAddress $emailAlias_previous
